// Code generated by "stringer -type=NodeHealthStatus"; DO NOT EDIT.

package handler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HEALTHY-0]
	_ = x[UNHEALTHY-1]
	_ = x[NOT_REACHABLE-2]
}

const _NodeHealthStatus_name = "HEALTHYUNHEALTHYNOT_REACHABLE"

var _NodeHealthStatus_index = [...]uint8{0, 7, 16, 29}

func (i NodeHealthStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NodeHealthStatus_index)-1 {
		return "NodeHealthStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeHealthStatus_name[_NodeHealthStatus_index[idx]:_NodeHealthStatus_index[idx+1]]
}
